"""build.bat must be reproducible on a clean Windows clone."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BAT = ROOT / "installer" / "build.bat"
PKG = ROOT / "frontend" / "package.json"
LOCK = ROOT / "frontend" / "yarn.lock"


def test_yarn_lockfile_is_classic_v1():
    assert LOCK.is_file(), "frontend/yarn.lock must be committed for a clean clone"
    text = LOCK.read_text(encoding="utf-8")
    assert text.startswith("# THIS IS AN AUTOGENERATED FILE.")
    assert "yarn lockfile v1" in text.splitlines()[1]
    assert "date-fns@4.1.0:" in text
    assert "react-day-picker@8.10.1:" in text


def test_package_manager_is_yarn_1_22_22():
    text = PKG.read_text(encoding="utf-8")
    assert '"packageManager": "yarn@1.22.22' in text


def test_build_bat_uses_corepack_yarn_not_npm_ci():
    text = BAT.read_text(encoding="utf-8")
    active = [
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.strip().upper().startswith("REM")
        and not line.strip().startswith("echo ")
    ]
    blob = "\n".join(active)
    assert "corepack yarn" in blob
    assert "--frozen-lockfile" in blob
    assert "call npm ci" not in blob
    assert "npm ci ||" not in blob
    assert "npm install --force" not in blob
    assert "yarn install --force" not in blob
    assert "--legacy-peer-deps" not in blob
    assert "yarn.lock" in blob
    assert "SignTool" not in blob


def test_build_bat_python_download_is_verified():
    text = BAT.read_text(encoding="utf-8")
    assert "download_url.py" in text
    assert "--expect-member python.exe" in text
    assert "download_python_zip" in text
    assert "verify_zip_nopy" in text
    assert "Refusing to extract" in text
